# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170626_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birday',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
    ]
